version: '3'

services:
  kt_mysql:
    image: mysql:latest
    container_name: kt_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: kt_laravel_db
      MYSQL_USER: kt_laravel_user
      MYSQL_PASSWORD: kt_laravel_password
    volumes:
      - kt_mysql_volume:/var/lib/mysql
    networks:
      - kt_network

  kt_php:
    build:
      dockerfile: devops/docker/php.dockerfile
    container_name: kt_php
    volumes:
      - ./:/var/www/html
    depends_on:
      - kt_mysql
    networks:
      - kt_network
      
  kt_nginx:
    image: nginx:latest
    container_name: kt_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./devops/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - kt_php
    networks:
      - kt_network

networks:
  kt_network:
    driver: bridge

volumes:
  kt_mysql_volume:
